title: Student Test Data Analysis and Visualizations
author: Adrian Allen
logo: logo.png

execute:
  execute_notebooks: force
  timeout: 300

repository:
  url: https://github.com/Aj-eloa/mlproject 
  path_to_book: test_analysis_book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image
    - colon_fence
    - linkify

sphinx:
  extra_extensions:
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.viewcode'
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      use_download_button: false
    nb_execution_mode: force

# Add this section to help with file path resolution
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Displaying interactive plotly figures
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js